<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\OAuthController;
use App\Http\Controllers\Api\CompanySettingController;
use App\Http\Controllers\Api\HomeController;
use App\Http\Controllers\Api\PackageController;
use App\Http\Controllers\Api\DestinationController;
use App\Http\Controllers\Api\HeroSlideController;
use App\Http\Controllers\Api\LocaleController;
use App\Http\Controllers\Api\SiteContentController;
use App\Http\Controllers\Api\BlogPostController;
use App\Http\Controllers\Api\ContactController;
use App\Http\Controllers\Api\PaymentController;
use App\Http\Controllers\Api\ReviewController;
use App\Http\Controllers\Api\NotificationController;
use App\Http\Controllers\Api\Admin\DashboardController as AdminDashboardController;
use App\Http\Controllers\Api\Admin\AgentController;
use App\Http\Controllers\Api\Admin\CompanySettingController as AdminCompanySettingController;
use App\Http\Controllers\Api\Admin\RolePermissionController;
use App\Http\Controllers\Api\Admin\ProfileController as AdminProfileController;
use App\Http\Controllers\Api\Admin\SiteContentController as AdminSiteContentController;
use App\Http\Controllers\Api\Admin\HomeContentController as AdminHomeContentController;
use App\Http\Controllers\Api\Agent\AnalyticsController as AgentAnalyticsController;
use App\Http\Controllers\Api\Agent\DashboardController as AgentDashboardController;
use App\Http\Controllers\Api\Agent\PackageController as AgentPackageController;
use App\Http\Controllers\Api\Agent\BlogPostController as AgentBlogPostController;
use App\Http\Controllers\Api\Agent\UserController as AgentUserController;
use App\Http\Controllers\Api\Agent\ReviewController as AgentReviewController;
use App\Http\Controllers\Api\Agent\InquiryController as AgentInquiryController;
use App\Http\Controllers\Api\Agent\BookingController as AgentBookingController;
use App\Http\Controllers\Api\Agent\PendingChangeController as AgentPendingChangeController;
use App\Http\Controllers\Api\Agent\PaymentSettingController as AgentPaymentSettingController;
use App\Http\Controllers\Api\Agent\ProfileController as AgentProfileController;
use App\Http\Controllers\Api\Agent\CrmController as AgentCrmController;
use App\Http\Controllers\Api\User\PaymentSettingController as UserPaymentSettingController;
use App\Http\Controllers\Api\User\ProfileController;
use App\Http\Controllers\Api\User\BookingController as UserBookingController;
use App\Http\Controllers\Api\User\PhotoController as UserPhotoController;
use App\Http\Controllers\Api\User\StaffMessageController as UserStaffMessageController;
use App\Http\Controllers\Api\User\SuggestionController as UserSuggestionController;
use App\Http\Controllers\Api\User\WishlistController as UserWishlistController;

Route::get('/locales', [LocaleController::class, 'index']);
Route::get('/company-settings', [CompanySettingController::class, 'show']);
Route::get('/site-content', [SiteContentController::class, 'index']);
Route::get('/site-content/{key}', [SiteContentController::class, 'show']);
Route::get('/home', [HomeController::class, 'index']);
Route::get('/packages', [PackageController::class, 'index']);
Route::get('/packages/{slug}', [PackageController::class, 'show']);
Route::get('/packages/{slug}/availability', [PackageController::class, 'availability']);
Route::get('/destinations', [DestinationController::class, 'index']);
Route::get('/hero-slides', [HeroSlideController::class, 'index']);
Route::get('/reviews', [ReviewController::class, 'index']);
Route::get('/blog-posts', [BlogPostController::class, 'index']);
Route::get('/blog-posts/{slug}', [BlogPostController::class, 'show']);
Route::post('/contact', [ContactController::class, 'store']);

Route::post('/auth/register', [AuthController::class, 'register']);
Route::post('/auth/login', [AuthController::class, 'login']);
Route::post('/auth/forgot-password', [AuthController::class, 'forgotPassword']);
Route::post('/auth/reset-password', [AuthController::class, 'resetPassword']);
Route::get('/auth/google/redirect', [OAuthController::class, 'redirect']);
Route::get('/auth/google/callback', [OAuthController::class, 'callback']);
Route::get('/payments/checkout-options', [PaymentController::class, 'checkoutOptions']);
Route::post('/payments/bookings', [PaymentController::class, 'storeBookingRequest'])->middleware('auth.optional');
Route::post('/payments/checkout', [PaymentController::class, 'createCheckoutSession'])->middleware('auth.optional');
Route::get('/payments/manual-booking', [PaymentController::class, 'showManualBooking']);
Route::get('/payments/verify', [PaymentController::class, 'verifySession']);
Route::post('/payments/webhook', [PaymentController::class, 'webhook']);

Route::middleware('auth:sanctum')->group(function () {
    Route::post('/auth/logout', [AuthController::class, 'logout']);
    Route::get('/auth/me', [AuthController::class, 'me']);
    Route::get('/notifications', [NotificationController::class, 'index']);
    Route::post('/notifications/read-all', [NotificationController::class, 'markAllRead']);
    Route::post('/notifications/{id}/read', [NotificationController::class, 'markRead']);

    Route::middleware('role:admin')->prefix('admin')->group(function () {
        Route::get('/dashboard', [AdminDashboardController::class, 'index']);
        Route::get('/profile', [AdminProfileController::class, 'show']);
        Route::put('/profile', [AdminProfileController::class, 'update']);
        Route::post('/profile', [AdminProfileController::class, 'update']);
        Route::get('/agents', [AgentController::class, 'index']);
        Route::post('/agents', [AgentController::class, 'store']);
        Route::put('/agents/{agent}', [AgentController::class, 'update']);
        Route::delete('/agents/{agent}', [AgentController::class, 'destroy']);
        Route::get('/role-permissions', [RolePermissionController::class, 'show']);
        Route::put('/role-permissions', [RolePermissionController::class, 'update']);
        Route::put('/role-permissions/{role}', [RolePermissionController::class, 'updateRole']);
        Route::get('/company-settings', [AdminCompanySettingController::class, 'show']);
        Route::put('/company-settings', [AdminCompanySettingController::class, 'update']);
        Route::post('/company-settings', [AdminCompanySettingController::class, 'update']);
        Route::get('/site-content', [AdminSiteContentController::class, 'show']);
        Route::put('/site-content', [AdminSiteContentController::class, 'update']);
        Route::post('/site-content/page_sections', [AdminSiteContentController::class, 'updatePageSections']);
        Route::post('/site-content/footer', [AdminSiteContentController::class, 'updateFooter']);
        Route::put('/site-content/{key}', [AdminSiteContentController::class, 'updateSection']);
        Route::get('/hero-slides', [AdminHomeContentController::class, 'heroSlides']);
        Route::post('/hero-slides', [AdminHomeContentController::class, 'storeHeroSlide']);
        Route::post('/hero-slides/{heroSlide}', [AdminHomeContentController::class, 'updateHeroSlide']);
        Route::delete('/hero-slides/{heroSlide}', [AdminHomeContentController::class, 'destroyHeroSlide']);
        Route::get('/destinations', [AdminHomeContentController::class, 'destinations']);
        Route::post('/destinations', [AdminHomeContentController::class, 'storeDestination']);
        Route::post('/destinations/{destination}', [AdminHomeContentController::class, 'updateDestination']);
        Route::delete('/destinations/{destination}', [AdminHomeContentController::class, 'destroyDestination']);
    });

    Route::middleware('role:agent')->prefix('agent')->group(function () {
        Route::get('/profile', [AgentProfileController::class, 'show'])->middleware('agent.permission:profile.view');
        Route::put('/profile', [AgentProfileController::class, 'update'])->middleware('agent.permission:profile.update');
        Route::post('/profile', [AgentProfileController::class, 'update'])->middleware('agent.permission:profile.update');
        Route::get('/dashboard', [AgentDashboardController::class, 'index'])->middleware('agent.permission:dashboard.view');
        Route::get('/analytics', [AgentAnalyticsController::class, 'index'])->middleware('agent.permission:analytics.view');
        Route::get('/packages', [AgentPackageController::class, 'index'])->middleware('agent.permission:packages.view');
        Route::post('/packages', [AgentPackageController::class, 'store'])->middleware('agent.permission:packages.create');
        Route::get('/packages/{package}', [AgentPackageController::class, 'show'])->middleware('agent.permission:packages.view');
        Route::put('/packages/{package}', [AgentPackageController::class, 'update'])->middleware('agent.permission:packages.update');
        Route::post('/packages/{package}', [AgentPackageController::class, 'update'])->middleware('agent.permission:packages.update');
        Route::delete('/packages/{package}', [AgentPackageController::class, 'destroy'])->middleware('agent.permission:packages.delete');
        Route::get('/blog-posts', [AgentBlogPostController::class, 'index'])->middleware('agent.permission:blog.view');
        Route::post('/blog-posts', [AgentBlogPostController::class, 'store'])->middleware('agent.permission:blog.create');
        Route::post('/blog-posts/{blogPost}', [AgentBlogPostController::class, 'update'])->middleware('agent.permission:blog.update');
        Route::delete('/blog-posts/{blogPost}', [AgentBlogPostController::class, 'destroy'])->middleware('agent.permission:blog.delete');
        Route::get('/users', [AgentUserController::class, 'index'])->middleware('agent.permission:users.view');
        Route::get('/users/export', [AgentUserController::class, 'export'])->middleware('agent.permission:users.view');
        Route::post('/users', [AgentUserController::class, 'store'])->middleware('agent.permission:users.create');
        Route::put('/users/{user}', [AgentUserController::class, 'update'])->middleware('agent.permission:users.update');
        Route::post('/users/{user}', [AgentUserController::class, 'update'])->middleware('agent.permission:users.update');
        Route::post('/users/{user}/approve', [AgentUserController::class, 'approve'])->middleware('agent.permission:users.approve');
        Route::post('/users/{user}/reject', [AgentUserController::class, 'reject'])->middleware('agent.permission:users.approve');
        Route::delete('/users/{user}', [AgentUserController::class, 'destroy'])->middleware('agent.permission:users.delete');
        Route::get('/payment-settings', [AgentPaymentSettingController::class, 'show'])->middleware('agent.permission:payment_settings.view');
        Route::put('/payment-settings', [AgentPaymentSettingController::class, 'update'])->middleware('agent.permission:payment_settings.update');
        Route::post('/payment-settings', [AgentPaymentSettingController::class, 'update'])->middleware('agent.permission:payment_settings.update');
        Route::get('/approvals', [AgentPendingChangeController::class, 'index'])->middleware('agent.permission:approvals.view');
        Route::post('/approvals/{pendingChange}/approve', [AgentPendingChangeController::class, 'approve'])->middleware('agent.permission:approvals.review');
        Route::post('/approvals/{pendingChange}/reject', [AgentPendingChangeController::class, 'reject'])->middleware('agent.permission:approvals.review');
        Route::get('/reviews', [AgentReviewController::class, 'index'])->middleware('agent.permission:reviews.view');
        Route::post('/reviews/{review}/approve', [AgentReviewController::class, 'approve'])->middleware('agent.permission:reviews.approve');
        Route::post('/reviews/{review}/reject', [AgentReviewController::class, 'reject'])->middleware('agent.permission:reviews.approve');
        Route::delete('/reviews/{review}', [AgentReviewController::class, 'destroy'])->middleware('agent.permission:reviews.delete');
        Route::get('/inquiries', [AgentInquiryController::class, 'index'])->middleware('agent.permission:inquiries.view');
        Route::patch('/inquiries/{inquiry}/status', [AgentInquiryController::class, 'updateStatus'])->middleware('agent.permission:inquiries.update');
        Route::get('/bookings', [AgentBookingController::class, 'index'])->middleware('agent.permission:bookings.view');
        Route::get('/bookings/export', [AgentBookingController::class, 'export'])->middleware('agent.permission:bookings.view');
        Route::post('/bookings/{booking}/approve', [AgentBookingController::class, 'approve'])->middleware('agent.permission:bookings.approve');
        Route::post('/bookings/{booking}/reject', [AgentBookingController::class, 'reject'])->middleware('agent.permission:bookings.approve');
        Route::get('/crm/summary', [AgentCrmController::class, 'summary'])->middleware('agent.permission:crm.view');
        Route::get('/crm/customers', [AgentCrmController::class, 'customers'])->middleware('agent.permission:crm.view');
        Route::get('/crm/customers/{user}', [AgentCrmController::class, 'showCustomer'])->middleware('agent.permission:crm.view');
        Route::post('/crm/customers/{user}/interactions', [AgentCrmController::class, 'storeInteraction'])->middleware('agent.permission:crm.interactions.create');
        Route::patch('/crm/customers/{user}/loyalty', [AgentCrmController::class, 'updateLoyalty'])->middleware('agent.permission:crm.campaigns.manage');
        Route::get('/crm/campaigns', [AgentCrmController::class, 'campaigns'])->middleware('agent.permission:crm.campaigns.view');
        Route::post('/crm/campaigns', [AgentCrmController::class, 'storeCampaign'])->middleware('agent.permission:crm.campaigns.manage');
        Route::post('/crm/campaigns/{campaign}/send', [AgentCrmController::class, 'sendCampaign'])->middleware('agent.permission:crm.campaigns.manage');
        Route::get('/crm/campaigns/{campaign}/recipients', [AgentCrmController::class, 'campaignRecipients'])->middleware('agent.permission:crm.campaigns.view');
    });

    Route::middleware('role:user')->prefix('user')->group(function () {
        Route::get('/profile', [ProfileController::class, 'show']);
        Route::put('/profile', [ProfileController::class, 'update']);
        Route::post('/profile', [ProfileController::class, 'update']);
        Route::get('/bookings/export', [UserBookingController::class, 'export']);
        Route::get('/bookings', [UserBookingController::class, 'index']);
        Route::get('/payment-settings', [UserPaymentSettingController::class, 'show']);
        Route::get('/staff-messages', [UserStaffMessageController::class, 'index']);
        Route::post('/staff-messages', [UserStaffMessageController::class, 'store']);
        Route::get('/wishlist', [UserWishlistController::class, 'index']);
        Route::post('/wishlist', [UserWishlistController::class, 'store']);
        Route::delete('/wishlist/{wishlistItem}', [UserWishlistController::class, 'destroy']);
        Route::get('/suggestions', [UserSuggestionController::class, 'index']);
        Route::post('/suggestions', [UserSuggestionController::class, 'store']);
        Route::get('/photos', [UserPhotoController::class, 'index']);
        Route::post('/photos', [UserPhotoController::class, 'store']);
        Route::delete('/photos/{photo}', [UserPhotoController::class, 'destroy']);
        Route::post('/reviews', [ReviewController::class, 'store']);
    });
});
