<?php

namespace Database\Seeders;

use App\Models\Package;
use Illuminate\Database\Seeder;

class PackageSeeder extends Seeder
{
    public function run(): void
    {
        $packages = [
            [
                'title' => 'Everest Base Camp Trek',
                'slug' => 'everest-base-camp-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
                'gallery_images' => [
                    'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
                    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
                    'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80',
                ],
                'short_description' => 'Trek to the base of the world\'s highest mountain through Sherpa villages and stunning Himalayan vistas.',
                'description' => 'The Everest Base Camp Trek is one of the most iconic journeys in the world. Walk through the Khumbu region, visit Tengboche Monastery, and stand at the foot of Mount Everest. Expert guides, comfortable teahouses, and unforgettable mountain scenery await.',
                'duration_days' => 16,
                'rating' => 5,
                'price' => 1499,
                'difficulty' => 'Moderate',
                'max_altitude' => 5364,
                'sort_order' => 1,
            ],
            [
                'title' => 'Annapurna Circuit Trek',
                'slug' => 'annapurna-circuit-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?w=800&q=80',
                'short_description' => 'A classic Himalayan circuit crossing Thorong La Pass with diverse landscapes and cultures.',
                'description' => 'Experience one of the greatest treks on earth. The Annapurna Circuit takes you from lush subtropical valleys to arid high-altitude terrain, crossing the Thorong La Pass at 5,416m with panoramic views of Annapurna and Dhaulagiri.',
                'duration_days' => 22,
                'rating' => 5,
                'price' => 1899,
                'difficulty' => 'Challenging',
                'max_altitude' => 5416,
                'sort_order' => 2,
            ],
            [
                'title' => 'Ghorepani Poon Hill Trek',
                'slug' => 'ghorepani-poon-hill-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
                'short_description' => 'A short and scenic trek with sunrise views over Annapurna and Dhaulagiri from Poon Hill.',
                'description' => 'Perfect for beginners and families, this trek offers rhododendron forests, Gurung villages, and one of the finest sunrise viewpoints in Nepal at Poon Hill (3,210m).',
                'duration_days' => 10,
                'rating' => 5,
                'price' => 899,
                'difficulty' => 'Easy',
                'max_altitude' => 3210,
                'sort_order' => 3,
            ],
            [
                'title' => 'Annapurna Base Camp Trek',
                'slug' => 'annapurna-base-camp-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80',
                'short_description' => 'Trek into the heart of the Annapurna Sanctuary surrounded by towering peaks.',
                'description' => 'Walk through bamboo forests and alpine meadows to reach Annapurna Base Camp, encircled by Annapurna I, Machapuchare, and Hiunchuli. A rewarding trek with moderate difficulty.',
                'duration_days' => 16,
                'rating' => 5,
                'price' => 1299,
                'difficulty' => 'Moderate',
                'max_altitude' => 4130,
                'sort_order' => 4,
            ],
            [
                'title' => 'Upper Mustang Trek',
                'slug' => 'upper-mustang-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80',
                'short_description' => 'Explore the forbidden kingdom of Lo with ancient monasteries and Tibetan culture.',
                'description' => 'Journey to the remote Upper Mustang region, a desert-like landscape dotted with cave monasteries, walled cities, and centuries-old Buddhist traditions.',
                'duration_days' => 18,
                'rating' => 5,
                'price' => 2199,
                'difficulty' => 'Moderate',
                'max_altitude' => 3840,
                'is_featured' => true,
                'sort_order' => 5,
            ],
            [
                'title' => 'Everest View Trek',
                'slug' => 'everest-view-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1454496522488-7a8e488e8606?w=800&q=80',
                'short_description' => 'Short trek with spectacular views of Everest, Lhotse, and Ama Dablam.',
                'description' => 'Ideal for those with limited time, this trek reaches Tengboche and offers close-up views of the Everest massif without going to base camp.',
                'duration_days' => 8,
                'rating' => 5,
                'price' => 999,
                'difficulty' => 'Easy',
                'max_altitude' => 3860,
                'is_featured' => true,
                'sort_order' => 6,
            ],
            [
                'title' => 'Everest Panorama Trek',
                'slug' => 'everest-panorama-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1488646953014-85cb44e25828?w=800&q=80',
                'short_description' => 'Panoramic views of the Everest region with comfortable daily hiking.',
                'description' => 'A well-paced introduction to the Khumbu with visits to Namche Bazaar, Khumjung village, and the famous Tengboche Monastery.',
                'duration_days' => 10,
                'rating' => 5,
                'price' => 1099,
                'difficulty' => 'Easy',
                'max_altitude' => 3860,
                'is_featured' => true,
                'sort_order' => 7,
            ],
            [
                'title' => 'Annapurna Short Trek',
                'slug' => 'annapurna-short-trek',
                'category' => 'trekking',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
                'short_description' => 'A compact Annapurna experience perfect for first-time trekkers.',
                'description' => 'Experience the beauty of the Annapurna region in just over a week with guided trails, local hospitality, and mountain views.',
                'duration_days' => 8,
                'rating' => 5,
                'price' => 799,
                'difficulty' => 'Easy',
                'max_altitude' => 2870,
                'is_featured' => true,
                'sort_order' => 8,
                'is_season_pick' => true,
            ],
            [
                'title' => 'Himalaya Helicopter Tour',
                'slug' => 'himalaya-helicopter-tour',
                'category' => 'tour',
                'country' => 'Nepal',
                'region' => 'Everest Region',
                'image' => 'https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80',
                'short_description' => 'Fly over the Himalayas and land at Everest Base Camp or Annapurna region.',
                'description' => 'Experience the grandeur of the Himalayas from above. Our helicopter tours offer breathtaking aerial views and optional landings at scenic viewpoints.',
                'itinerary' => "Day 1: Arrival in Kathmandu and trip briefing.\n\nDay 2: Scenic helicopter flight with mountain views.\n\nDay 3: Main helicopter tour with optional landing.\n\nDay 4: Departure transfer.",
                'availability_pricing' => 'Available year-round subject to weather. Best seasons: March-May and September-November. Contact us for group and private pricing.',
                'duration_days' => 4,
                'rating' => 5,
                'price' => 2499,
                'difficulty' => 'Moderate',
                'difficulty_score' => 3,
                'group_size_min' => 1,
                'group_size_max' => 6,
                'is_featured' => true,
                'sort_order' => 9,
            ],
            [
                'title' => 'Nepal Photography Tour',
                'slug' => 'nepal-photography-tour',
                'category' => 'tour',
                'image' => 'https://images.unsplash.com/photo-1526401485004-2aa4f687b106?w=800&q=80',
                'short_description' => 'Capture Nepal\'s landscapes, culture, and wildlife with expert photo guides.',
                'description' => 'From Kathmandu\'s heritage sites to mountain viewpoints and wildlife safaris in Chitwan, this tour is designed for photography enthusiasts.',
                'duration_days' => 14,
                'rating' => 5,
                'price' => 1799,
                'is_featured' => true,
                'sort_order' => 10,
            ],
            [
                'title' => 'Himalaya Highlights Tours',
                'slug' => 'himalaya-highlights-tours',
                'category' => 'tour',
                'image' => 'https://images.unsplash.com/photo-1548013146-72479768bada?w=800&q=80',
                'short_description' => 'The best of Nepal in one journey — culture, nature, and adventure.',
                'description' => 'Visit Kathmandu Valley UNESCO sites, enjoy a short trek, and experience a jungle safari. The perfect introduction to Nepal.',
                'duration_days' => 10,
                'rating' => 5,
                'price' => 1299,
                'is_featured' => true,
                'sort_order' => 11,
            ],
            [
                'title' => 'Nepal Explore Tour',
                'slug' => 'nepal-explore-tour',
                'category' => 'tour',
                'image' => 'https://images.unsplash.com/photo-1526779255127-6a2568040ab9?w=800&q=80',
                'short_description' => 'Comprehensive tour covering Nepal\'s cultural and natural highlights.',
                'description' => 'Explore ancient temples, hill stations, lakeside Pokhara, and traditional villages on this curated 10-day tour.',
                'duration_days' => 10,
                'rating' => 5,
                'price' => 1199,
                'is_featured' => true,
                'sort_order' => 12,
            ],
            [
                'title' => 'ZipFlyer Nepal Adventure',
                'slug' => 'zipflyer-nepal-adventure',
                'category' => 'adventure',
                'image' => 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?w=800&q=80',
                'short_description' => 'The ultimate zipline experience with views of the Annapurna range.',
                'description' => 'Soar at speeds up to 140 km/h on one of the world\'s longest, steepest, and fastest ziplines with panoramic Himalayan views.',
                'duration_days' => 1,
                'rating' => 5,
                'price' => 120,
                'sort_order' => 13,
            ],
            [
                'title' => 'White Water Rafting',
                'slug' => 'white-water-rafting',
                'category' => 'adventure',
                'image' => 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800&q=80',
                'short_description' => 'Thrilling rafting on Nepal\'s world-famous rivers.',
                'description' => 'Navigate the Trishuli, Bhote Koshi, or Sun Koshi rivers with experienced guides. Suitable for beginners and adrenaline seekers alike.',
                'duration_days' => 2,
                'rating' => 5,
                'price' => 199,
                'sort_order' => 14,
            ],
            [
                'title' => 'Paragliding in Pokhara',
                'slug' => 'paragliding-pokhara',
                'category' => 'adventure',
                'image' => 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
                'short_description' => 'Fly over Phewa Lake with Annapurna peaks as your backdrop.',
                'description' => 'Pokhara is one of the best paragliding destinations in the world. Tandem flights with certified pilots offer an unforgettable aerial adventure.',
                'duration_days' => 1,
                'rating' => 5,
                'price' => 95,
                'sort_order' => 15,
            ],
        ];

        foreach ($packages as $package) {
            Package::create($package);
        }
    }
}
